version: '3'

tasks:
  build:
    cmds:
      - cargo leptos build
      - LEPTOS_SITE_ROOT="." cargo lambda build --no-default-features --features=ssr --arm64
      - cargo run --bin vercel --features ssr
    env:
      LEPTOS_OUTPUT_NAME: pipedream
  release:
    cmds:
      - cargo leptos build --release
      - LEPTOS_SITE_ROOT="." cargo lambda build --release --no-default-features --features=ssr --arm64
      - cargo run --bin vercel --features ssr
      - vercel deploy --prebuilt --prod
    env:
      LEPTOS_OUTPUT_NAME: pipedream
